# Generated by Django 3.0.5 on 2020-05-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DownloadHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("celery_id", models.UUIDField(blank=True, null=True)),
                ("video_file", models.FileField(blank=True, null=True, upload_to="")),
                ("youtube_url", models.URLField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("preparing", "Preparing"),
                            ("downloading", "Downloading"),
                            ("finished", "Finished"),
                        ],
                        default="preparing",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
